export const insights = [
  { value: "SBIN000145" },
  { value: "Rohit Sharma" },
  { value: "Delhi Main Branch Plaza" },
  { value: "Delhi" },
  { value: "HOLD BAN" },
  { value: "Disabled" },
  { value: "783912" },
  { value: "982314" },
  { value: "Kolkata Main Office" },
  { value: "HDFC000123" },
  { value: "Payee Verified" },
  { value: "No Restrictions" },
  { value: "PENDING REVIEW" },
  { value: "Invalid Account Number" },
  { value: "Active Account" },
];

export const fraudSignalsData = [
  {
    id: 1,
    signal: "Image Manipulation",
    status: "POSSIBLE_IMAGE_MANIPULATION",
  },
  { id: 2, signal: "Is Identity Document", status: "PASS" },
  { id: 3, signal: "Online Duplicate", status: "FAIL" },
  { id: 4, signal: "Photocopy Detection", status: "PASS" },
  { id: 5, signal: "Blur Detection", status: "FAIL" },
  { id: 6, signal: "Low Resolution Image", status: "FAIL" },
  { id: 7, signal: "Face Mismatch", status: "POSSIBLE_MANIPULATION" },
  { id: 8, signal: "Invalid File Format", status: "FAIL" },
  { id: 9, signal: "Watermark Detected", status: "POSSIBLE_FRAUD" },
  { id: 10, signal: "Suspicious Metadata", status: "FAIL" },
  { id: 11, signal: "Tampering Detected", status: "POSSIBLE_MANIPULATION" },
  { id: 12, signal: "Overexposure", status: "PASS" },
  { id: 13, signal: "Shadow Inconsistencies", status: "FAIL" },
  { id: 14, signal: "Incorrect Aspect Ratio", status: "PASS" },
  { id: 15, signal: "Background Mismatch", status: "POSSIBLE_MANIPULATION" },
];
